In [1]:
import pandas as pd
import numpy as np

### 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
number_of_throws = number_of_rows = 3333
number_of_dice = number_of_columns = 2

In [6]:
throws = np.random.choice([1,2,3,4,5,6], number_of_rows * number_of_columns).reshape(number_of_rows, number_of_columns)

In [7]:
throws

array([[3, 4],
       [3, 3],
       [6, 5],
       ...,
       [1, 2],
       [2, 3],
       [3, 5]])

In [20]:
outcomes = []
for throw in throws:
    if throw[0] == throw[1]:
        outcomes.append(True)
    else:
        outcomes.append(False)

In [27]:
np.array(outcomes).mean()

0.1692169216921692

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [28]:
number_of_flips = number_of_rows = 3333
number_of_coins = number_of_columns = 8

In [49]:
# Create an array of zeros(0) and ones(1) that represent either heads or tails for eight flips.
outcomes = np.random.choice([0,1], number_of_rows * number_of_columns).reshape(number_of_rows, number_of_columns)

In [51]:
outcomes

array([[1, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 1, 1]])

In [57]:
# Create an array of total amount of heads thrown per trial.
number_of_heads = outcomes.sum(axis=1)

In [60]:
# Find each trial where a total of three(3) heads were thrown.
three_heads = number_of_heads == 3

In [61]:
three_heads

array([False, False,  True, ..., False, False, False])

In [63]:
# The probability that three(3) heads will be thrown.
three_heads.mean()

0.2076207620762076

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [64]:
number_of_rows = number_of_picks = 3333
number_of_bilboards = number_of_columns = 2

probability_of_ds_student = .25
probability_of_wd_student = .75

In [67]:
# Create a two-dimensional array that returns True if the student chosen is a data science student.
billboard_choices = np.random.choice([True,False], number_of_columns*number_of_rows, p=[.25,.75]).reshape(number_of_rows,number_of_columns)

In [68]:
billboard_choices

array([[False, False],
       [False, False],
       [ True,  True],
       ...,
       [ True, False],
       [False,  True],
       [False, False]])

In [76]:
# Create an array that holds the sum of the values of each trial.
billboard_choices.sum(axis=1)

array([0, 0, 2, ..., 1, 1, 0])

In [71]:
# Create an array that returns True if both students chosen were data science students.
billboard_choices.sum(axis=1) == 2

array([False, False,  True, ..., False, False, False])

In [74]:
# Find the probability that both billboards will have a data science student.
(billboard_choices.sum(axis=1) == 2).mean()

0.06450645064506451

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [99]:
number_of_rows = 3333
number_of_columns = 5

mu = 3
sigma = 1.5

bye_bye_poptarts = np.random.normal(mu, sigma, number_of_rows*number_of_columns).astype(int).reshape(number_of_rows, number_of_columns)

In [100]:
bye_bye_poptarts

array([[1, 2, 1, 3, 4],
       [2, 0, 2, 0, 5],
       [2, 2, 6, 1, 3],
       ...,
       [3, 0, 1, 4, 1],
       [4, 5, 0, 4, 0],
       [3, 2, 1, 2, 1]])

In [101]:
(bye_bye_poptarts.sum(axis=1) < 17).mean()

0.885988598859886

### 5. Compare Heights
* Men have an average height of 178 cm and standard deviation of 8cm.
* Women have a mean of 170, sd = 6cm.
* Since you have means and standard deviations, you can use np.random.normal to generate observations.
* If a man and woman are chosen at random, P(woman taller than man)?

In [111]:
men_mu = 178
men_sigma = 8
women_mu = 170
women_sigma = 6

number_of_rows = 3333
number_of_columns = 1

men_array = np.random.normal(men_mu, men_sigma, number_of_rows * number_of_columns)
women_array = np.random.normal(women_mu, women_sigma, number_of_rows * number_of_columns)

In [114]:
men_array

array([183.71682673, 179.13710488, 185.42302214, ..., 193.66845493,
       174.54391424, 181.60631026])

In [113]:
women_array

array([173.70917796, 161.62730951, 161.10783264, ..., 171.19805262,
       167.14186981, 171.52796502])

In [116]:
df = {'men': men_array, 'women': women_array}

In [117]:
df

{'men': array([183.71682673, 179.13710488, 185.42302214, ..., 193.66845493,
        174.54391424, 181.60631026]),
 'women': array([173.70917796, 161.62730951, 161.10783264, ..., 171.19805262,
        167.14186981, 171.52796502])}

In [118]:
df = pd.DataFrame(df)

In [120]:
df['taller_woman'] = df.women > df.men

In [122]:
df

men       women  taller_woman
0     183.716827  173.709178         False
1     179.137105  161.627310         False
2     185.423022  161.107833         False
3     163.379700  173.579963          True
4     170.989498  169.003412         False
...          ...         ...           ...
3328  182.139952  179.111269         False
3329  179.726719  168.108867         False
3330  193.668455  171.198053         False
3331  174.543914  167.141870         False
3332  181.606310  171.527965         False

[3333 rows x 3 columns]

In [123]:
df.taller_woman.mean()

0.20522052205220523

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue?

In [126]:
probability_of_failure = 0.004

number_of_rows = 3333
number_of_columns = number_of_students = 50

download_outcomes = np.random.choice([True,False], number_of_columns*number_of_rows, p=[0.004,0.996]).reshape(number_of_rows,number_of_students)

In [135]:
(download_outcomes.sum(axis=1) == 0).mean()

0.8172817281728173

### What are the odds that after having 100 students download anaconda, no one has an installation issue?

In [136]:
probability_of_failure = 0.004

number_of_rows = 3333
number_of_columns = number_of_students = 100

download_outcomes = np.random.choice([True,False], number_of_columns*number_of_rows, p=[0.004,0.996]).reshape(number_of_rows,number_of_students)

In [137]:
(download_outcomes.sum(axis=1) == 0).mean()

0.6618661866186618

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [138]:
probability_of_failure = 0.004

number_of_rows = 3333
number_of_columns = number_of_students = 150

download_outcomes = np.random.choice([True,False], number_of_columns*number_of_rows, p=[0.004,0.996]).reshape(number_of_rows,number_of_students)

In [139]:
(download_outcomes.sum(axis=1) == 0).mean()

0.5538553855385538

### How likely is it that 450 students all download anaconda without an issue?

In [140]:
probability_of_failure = 0.004

number_of_rows = 3333
number_of_columns = number_of_students = 450

download_outcomes = np.random.choice([True,False], number_of_columns*number_of_rows, p=[0.004,0.996]).reshape(number_of_rows,number_of_students)

In [141]:
(download_outcomes.sum(axis=1) == 0).mean()

0.17311731173117312

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [144]:
food_truck_probability = 0.70

number_of_rows = 3333
number_of_columns = 3

food_truck_outcomes = np.random.choice([True,False], number_of_rows*number_of_columns, p=[0.70, 0.30]).reshape(number_of_rows,number_of_columns)

In [145]:
food_truck_outcomes

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       ...,
       [ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [147]:
food_truck_outcomes.sum(axis=1)

array([3, 3, 3, ..., 2, 3, 2])

In [151]:
(food_truck_outcomes.sum(axis=1) == 0).mean()

0.030903090309030903

### How likely is it that a food truck will show up sometime this week?

In [155]:
def food_truck(days):
    number_of_rows = 3333
    number_of_columns = days
    
    food_truck_outcomes = np.random.choice([True,False], number_of_rows*number_of_columns, p=[0.70, 0.30]).reshape(number_of_rows,number_of_columns)
    probability = (food_truck_outcomes.sum(axis=1) == 0).mean()
    
    print(f'The probability of not seeing a food truck in {days} consecutive days is: {round(probability*100)}%')

In [157]:
food_truck(2)

The probability of not seeing a food truck in 2 consecutive days is: 10%


In [158]:
for r in range(1,8):
    food_truck(r)
    print()

The probability of not seeing a food truck in 1 consecutive days is: 30%

The probability of not seeing a food truck in 2 consecutive days is: 10%

The probability of not seeing a food truck in 3 consecutive days is: 3%

The probability of not seeing a food truck in 4 consecutive days is: 1%

The probability of not seeing a food truck in 5 consecutive days is: 0%

The probability of not seeing a food truck in 6 consecutive days is: 0%

The probability of not seeing a food truck in 7 consecutive days is: 0%



### If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [170]:
def shared_birthdays(students):
    number_of_rows = 3333
    number_of_columns = students
    
    sightings = np.random.choice([r for r in range(366)], number_of_rows * number_of_columns).reshape(number_of_rows, number_of_columns)
    df = pd.DataFrame(sightings)
    df['duplicate_birthday'] = df.nunique(axis=1) < number_of_columns
    matching_birthdays = df.duplicate_birthday.mean()
    print(f'The probability that at least two people share the same birthday in a room of {students} students is: {matching_birthdays}')

In [176]:
shared_birthdays(23)

The probability that at least two people share the same birthday in a room of 23 students is: 0.5028502850285028


### What if it's 20 people?

In [177]:
shared_birthdays(20)

The probability that at least two people share the same birthday in a room of 20 students is: 0.4146414641464146


### 40?

In [178]:
shared_birthdays(40)

The probability that at least two people share the same birthday in a room of 40 students is: 0.8967896789678967
