In [1]:
import pandas as pd
import numpy as np

### 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
number_of_throws = number_of_rows = 3333
number_of_dice = number_of_columns = 2

In [6]:
throws = np.random.choice([1,2,3,4,5,6], number_of_rows * number_of_columns).reshape(number_of_rows, number_of_columns)

In [7]:
throws

array([[3, 4],
       [3, 3],
       [6, 5],
       ...,
       [1, 2],
       [2, 3],
       [3, 5]])

In [20]:
outcomes = []
for throw in throws:
    if throw[0] == throw[1]:
        outcomes.append(True)
    else:
        outcomes.append(False)

In [27]:
np.array(outcomes).mean()

0.1692169216921692

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [28]:
number_of_flips = number_of_rows = 3333
number_of_coins = number_of_columns = 8

In [49]:
# Create an array of zeros(0) and ones(1) that represent either heads or tails for eight flips.
outcomes = np.random.choice([0,1], number_of_rows * number_of_columns).reshape(number_of_rows, number_of_columns)

In [51]:
outcomes

array([[1, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 1, 1]])

In [57]:
# Create an array of total amount of heads thrown per trial.
number_of_heads = outcomes.sum(axis=1)

In [60]:
# Find each trial where a total of three(3) heads were thrown.
three_heads = number_of_heads == 3

In [61]:
three_heads

array([False, False,  True, ..., False, False, False])

In [63]:
# The probability that three(3) heads will be thrown.
three_heads.mean()

0.2076207620762076

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [64]:
number_of_rows = number_of_picks = 3333
number_of_bilboards = number_of_columns = 2

probability_of_ds_student = .25
probability_of_wd_student = .75

In [67]:
# Create a two-dimensional array that returns True if the student chosen is a data science student.
billboard_choices = np.random.choice([True,False], number_of_columns*number_of_rows, p=[.25,.75]).reshape(number_of_rows,number_of_columns)

In [68]:
billboard_choices

array([[False, False],
       [False, False],
       [ True,  True],
       ...,
       [ True, False],
       [False,  True],
       [False, False]])

In [76]:
# Create an array that holds the sum of the values of each trial.
billboard_choices.sum(axis=1)

array([0, 0, 2, ..., 1, 1, 0])

In [71]:
# Create an array that returns True if both students chosen were data science students.
billboard_choices.sum(axis=1) == 2

array([False, False,  True, ..., False, False, False])

In [74]:
# Find the probability that both billboards will have a data science student.
(billboard_choices.sum(axis=1) == 2).mean()

0.06450645064506451